---
- name: Uninstall old versions of Docker if present
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    autoremove: true
  become: true

- name: Install APT prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  become: true

- name: Create directory for APT keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download Docker’s official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add Docker APT repository (signed-by keyring)
  ansible.builtin.apt_repository:
    filename: docker
    repo: >-
      deb [arch=amd64
           signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/debian
          bookworm stable
    update_cache: yes
  become: true


- name: Install Docker Engine, CLI, containerd, Buildx & Compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  become: true

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true

- name: Add current user to docker group for non-root Docker
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true

