---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  roles:
    - role: gantsign.golang
      golang_gopath: "{{ ansible_env.HOME }}/go"
    - role: "roles/install-tools"
    - role: "roles/configure-tmux"
    - role: "roles/configure-vim"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    - role: "roles/configure-system"
    - role: gantsign.visual-studio-code
    - role: "roles/clean-up"
