---
- name: Disable apt systemd timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - apt-daily.timer
    - apt-daily-upgrade.timer
  become: true

- name: Prevent apt services from running
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: true
  loop:
    - apt-daily.service
    - apt-daily-upgrade.service
  become: true
