---
- name: "Set QTerminal transparency to 0%"
  ansible.builtin.ini_file:
    path: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal.ini"
    section: General
    option: TerminalTransparency
    value: "0"
    backup: no
  become: false

- name: "Set Application Transparency to 0%"
  ansible.builtin.ini_file:
    path: "{{ ansible_env.HOME }}/.config/qterminal.org/qterminal.ini"
    section: MainWindow
    option: ApplicationTransparency
    value: 0
    backup: no
  become: false
